#!/usr/bin/env bash
# Displays the type and destination of subdomains for a given domain

# Function to display info about a subdomain
get_subdomain_info() {
    local subdomain=$1
    local ip

    case $subdomain in
        www)
            ip="54.210.47.110"
            ;;
        lb-01)
            ip="54.210.47.110"
            ;;
        web-01)
            ip="34.198.248.145"
            ;;
        web-02)
            ip="54.89.38.100"
            ;;
        *)
            ip="Unknown"
            ;;
    esac

    echo "The subdomain $subdomain is a A record and points to $ip"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # If no subdomain provided, display default subdomains
    for sd in www lb-01 web-01 web-02; do
        get_subdomain_info $sd
    done
else
    # Display info for the specific subdomain
    get_subdomain_info $subdomain
fi
